### ISSUE TITLE
Name of 'Work on' task in prompt is incorrect

### ISSUE THREAD

**Issue by ksalzke** [ksalzke/work-on-omnifocus-plug-in#2]
Currently showing '1' rather than the task name

**Comment by apkawel** [comment]
I've never used git to pull/push etc. (sorry) but I solved this issue and will leave the solution here for you to modify your code.

Line 15 in workOnLib.js should be corrected to read: `const trimmedName = match[1]`

I hope it helps! Thanks a *ton* for your plug-ins! They're fantastic! I found you via your YouTube interview on Learn OmniFocus.

**Comment by ksalzke** [comment]
Thanks @apkawel! Change made, and so glad you've found my plug-ins useful!
