### ISSUE TITLE
If original task name ends in a closing parenthesis → ) , the "Work on:" task cuts off the parenthesis

### ISSUE THREAD

**Issue by apkawel** [ksalzke/work-on-omnifocus-plug-in#3]
What happens:

1. Original task: "Buy a present for Dave's birthday (4/15)"
2. Run the "Add 'Work on…' task" automation on the original task
3. Output: "Buy a present for Dave's birthday (4/15"

What should happen: the closing parenthesis should not be cut off.

**Comment by apkawel** [comment]
Again, I don't know how to use git (sorry) but the solution to this bug is this:

line 6 in workOnLib.js should read: `const trimmedName = task.name.match(/\W.*\W/g)[0]`

The original regex was matching word characters at the ends instead of non-word characters. Capitalizing the Ws should solve the problem. Hope it helps!

**Comment by apkawel** [comment]
I don't know how to use git (sorry again) but I found the solution:

Line 6 in workOnLib.js should read: `const trimmedName = task.name.match(/\S.*\S/g)[0]`

The `\w` used in the original regex was dropping non-word characters (like a closed-parenthesis at the end of the task name). By using `\S` instead, the fix greedily matches (I believe) the longest string from one non-whitespace character to another non-whitespace character. This has the effect of trimming whitespace from the beginning and end of the task name while still picking up important non-word characters like parentheses.

I hope it helps!

**Comment by ksalzke** [comment]
Thanks @apkawel! I'd noticed this bug too but hadn't gotten around to doing anything to fix it.

Now fixed!
